# Generated by Django 5.0.1 on 2024-11-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dashboard', '0002_dashboardentry_icon_url_dashboardentry_is_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardentry',
            name='groups',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
