# Generated by Django 5.2.6 on 2025-09-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dashboard', '0003_dashboardentry_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardentry',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
