#!/bin/bash

# Check if module already is installed (is /root/addon.id directory present?)
if [ -d "/root/{{addon.id}}" ]; then
    echo "Module {{addon.id}} is already installed."
    exit 0
fi

echo "Installing module {{addon.id}}..."

mkdir -p /root/{{addon.id}}

# Copy icon to /var/www/libre-workspace-static/lac/icons
FILE_ENDINGS=".png .jpg .jpeg .svg .webp"
for ending in $FILE_ENDINGS; do
    if [ -f "/usr/lib/libre-workspace/modules/{{addon.id}}/{{addon.id}}$ending" ]; then
        cp "/usr/lib/libre-workspace/modules/{{addon.id}}/{{addon.id}}$ending" "/var/www/libre-workspace-static/lac/icons/{{addon.id}}$ending"
        break
    fi
done

. /etc/libre-workspace/libre-workspace.env

cd /usr/lib/libre-workspace/modules/{{addon.id}}

. setup_{{addon.id}}.sh