# Generated by Django 5.2.1 on 2025-06-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='permissions',
            field=models.TextField(blank=True, default='', help_text='Comma-separated list of permissions granted to this API key'),
        ),
    ]
