# Generated by Django 5.2.1 on 2025-06-28 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idm', '0002_apikey_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinuxClientUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dn', models.CharField(help_text='Distinguished Name of the user in LDAP', max_length=255, unique=True)),
                ('yescrypt_hash', models.CharField(help_text="The yescrypt hash of the user's password", max_length=255)),
            ],
        ),
    ]
